### ISSUE TITLE
WEB Extend client registration form

### ISSUE THREAD

**Issue by marcin-pwr** [marcin-pwr/hotel#10]
- add address and phone support  (now there are hardcoded strings persistence in user controller)

**Comment by marcin-pwr** [comment]
@KJRG can you take it? there will be some fixes in registration template, then in controller there should be some service method invoke and in service there should be population of client and address objects. Now as you can see there is everything done in controller and moreover there are only hardcoded strings persisted by entity manager. If such logic will be in service we could later use it while adding new client by reception or from desktop app..

**Comment by KJRG** [comment]
@marcin-pwr I can take it.

**Comment by marcin-pwr** [comment]
Here you are.

**Comment by marcin-pwr** [comment]
Ok registration works, some improvements like ex. asynchronous request and client triggered redirect to be done in future :)
