### ISSUE TITLE
WEB Alerts color dynamic class as text inclusion in thymeleaf

### ISSUE THREAD

**Issue by marcin-pwr** [marcin-pwr/hotel#15]
Hi, I have one question regarding thymeleaf. Do you know how to perform inline class inclusion, here is some sample code from our project:
```

<div class="col-sm-12 col-md-12" id="alerts-container">
				<div th:each="msg,i : ${messages}" th:classappend="alert-warning" class="alert alert-dismissible affix-top alert-nice" role="alert">
```

**ch="msg,i : ${messages}" th:classappend="alert-_warning_" class=**

The part which is bolded and italic "warning" should be taken from msg.status attribute, I'm not able to do such thing, how to achieve that? @KJRG have you got some experience with thymeleaf? I found some solution regarding inline text and usage of such construct  [[${msg.status}]] but it kinda not work.. ehh in Django it's so simple :smile:

**Comment by KJRG** [comment]
Found these:
- http://www.thymeleaf.org/doc/tutorials/2.1/usingthymeleaf.html (paragraph 5.4 Appending and prepending)
- http://stackoverflow.com/questions/23737836/if-else-in-a-theach-statement-in-thymeleaf
Try:
th:classappend="${msg.status}"

**Comment by marcin-pwr** [comment]
Thanks :smiley:
